### PR TITLE
Fix bug for start time exception

### LINKED ISSUE #87: Bugfix for start time after end time exception

### PR DESCRIPTION
**Pull request by Juggernaut102**
closes #87

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -86,7 +86,13 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         Person personToEdit = lastShownList.get(index.getZeroBased());
-        Person editedPerson = createEditedPerson(personToEdit, editPersonDescriptor);
+        Person editedPerson;
+        try {
+            editedPerson = createEditedPerson(personToEdit, editPersonDescriptor);
+        } catch (IllegalArgumentException e) {
+            // display start time after end time exception
+            throw new CommandException(e.getMessage());
```
Comment (Bleng-flash) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: Amazing !
